 #This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
 workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
        
 schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '8'
    - run: npm install 
    - run: npm run update-readme
    - run: |
          date > generated.txt
          git config user.name joanpaucg
          git config user.email joanpau.castells@hotmail.com
          git add .
          git commit -m " My github action cron: update readme with the latest info"
          git push
    
